version: '1.0'
name: nextflow

services:
  dind:
    image: docker:dind
    privileged: true
    expose:
      - 2375
      - 2376
    environment:
      DOCKER_TLS_CERTDIR: ""
    volumes:
      - ..:/workspace:rw

  nextflow:
    build: .
    privileged: true
    volumes:
      - ..:/workspace:rw
    working_dir: /workspace
    entrypoint: sleep 365d
    links:
      - dind
    environment:
      DOCKER_HOST: tcp://dind:2375/
